### ISSUE TITLE
hi 

### ISSUE THREAD

**Issue by yvan** [Blankpanda/GE_wrapper#1]
my issue is that i am not as awesome as your software. 

please help.

**Comment by Blankpanda** [comment]
its a work in progress

**Comment by yvan** [comment]
aren't we all.

i just noticed you popping up on pypi and thought i'd say hi.

things get kinda ... sketch at night in a lab.

**Comment by yvan** [comment]
i wanted to make something like this for WoW trade chat a while back.

but bliz api is weird and i hear trade chat is lame now.

**Comment by Blankpanda** [comment]
I was likely generating A LOT of traffic on PyPi, I was having trouble getting the package to recognize one my datafiles (not sure how to word it).  thank you stackoverflow.  Trade chat is pretty lame these days, use to be a little less tame.

**Comment by yvan** [comment]
yeah man .... i was having a similar issue ... and i kept seeing this on the front page.

see you around.
